# This is an example of a configuration file, that only contains comments.
# By not containing any content, we test cases where tokens are present
# but there is nothing that would parse into anything of value.


# Good to have some whitespace followed by another comment block for good
# measure.
