# This is an example of a really short configuration file, that will parse into
# at most 64 lexical tokens. Like `cargo.lock.conf`, this file is also based on
# this project's Cargo.lock file (although the lock file has since been modified
# and the range of acceptable characters in identifiers has expanded).

version = 4

aho_corasick: {
    version = "1.1.3"
    source = "registry+https://github.com/rust-lang/crates.io-index"
    checksum = "8e60d3430d3a69478ad0993f19238d2df97c507009a52b3c10addcd7f6bcb916"
    dependencies += "memchr"
}
