DOMAIN_NAMES += .
DOMAIN_NAMES += A.ROOT-SERVERS.NET.
DOMAIN_NAMES += B.ROOT-SERVERS.NET.
DOMAIN_NAMES += C.ROOT-SERVERS.NET.
DOMAIN_NAMES += D.ROOT-SERVERS.NET.
DOMAIN_NAMES += E.ROOT-SERVERS.NET.
DOMAIN_NAMES += F.ROOT-SERVERS.NET.
DOMAIN_NAMES += G.ROOT-SERVERS.NET.
DOMAIN_NAMES += H.ROOT-SERVERS.NET.
DOMAIN_NAMES += I.ROOT-SERVERS.NET.
DOMAIN_NAMES += J.ROOT-SERVERS.NET.
DOMAIN_NAMES += K.ROOT-SERVERS.NET.
DOMAIN_NAMES += L.ROOT-SERVERS.NET.
DOMAIN_NAMES += M.ROOT-SERVERS.NET.

TIMEOUT = 3600000
.: {
    NS += A.ROOT-SERVERS.NET.
    NS += B.ROOT-SERVERS.NET.
    NS += C.ROOT-SERVERS.NET.
    NS += D.ROOT-SERVERS.NET.
    NS += E.ROOT-SERVERS.NET.
    NS += F.ROOT-SERVERS.NET.
    NS += G.ROOT-SERVERS.NET.
    NS += H.ROOT-SERVERS.NET.
    NS += I.ROOT-SERVERS.NET.
    NS += J.ROOT-SERVERS.NET.
    NS += K.ROOT-SERVERS.NET.
    NS += L.ROOT-SERVERS.NET.
    NS += M.ROOT-SERVERS.NET.
}
A.ROOT-SERVERS.NET.: {
    A    = 198.41.0.4
    AAAA = 2001:503:ba3e::2:30
}
B.ROOT-SERVERS.NET.: {
    A    = 170.247.170.2
    AAAA = 2801:1b8:10::b
}
C.ROOT-SERVERS.NET.: {
    A    = 192.33.4.12
    AAAA = 2001:500:2::c
}
D.ROOT-SERVERS.NET.: {
    A    = 199.7.91.13
    AAAA = 2001:500:2d::d
}
E.ROOT-SERVERS.NET.: {
    A    = 192.203.230.10
    AAAA = 2001:500:a8::e
}
F.ROOT-SERVERS.NET.: {
    A    = 192.5.5.241
    AAAA = 2001:500:2f::f
}
G.ROOT-SERVERS.NET.: {
    A    = 192.112.36.4
    AAAA = 2001:500:12::d0d
}
H.ROOT-SERVERS.NET.: {
    A    = 198.97.190.53
    AAAA = 2001:500:1::53
}
I.ROOT-SERVERS.NET.: {
    A    = 192.36.148.17
    AAAA = 2001:7fe::53
}
J.ROOT-SERVERS.NET.: {
    A    = 192.58.128.30
    AAAA = 2001:503:c27::2:30
}
K.ROOT-SERVERS.NET.: {
    A    = 193.0.14.129
    AAAA = 2001:7fd::1
}
L.ROOT-SERVERS.NET.: {
    A    = 199.7.83.42
    AAAA = 2001:500:9f::42
}
M.ROOT-SERVERS.NET.: {
    A    = 202.12.27.33
    AAAA = 2001:dc3::35
}
